### ISSUE TITLE
Bug with pathlib on windows

### ISSUE THREAD

**Issue by Toliak** [Toliak/YandexDiskUploader#2]
```
Traceback (most recent call last):
  File "C:\Users\Toliak\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Toliak\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Toliak\AppData\Local\Programs\YandexDiskRSync\yandex_disk_rsync\__main__.py", line 4, in <module>
    cli_main()
  File "C:\Users\Toliak\AppData\Local\Programs\YandexDiskRSync\yandex_disk_rsync\__init__.py", line 224, in cli_main
    return main(args)
  File "C:\Users\Toliak\AppData\Local\Programs\YandexDiskRSync\yandex_disk_rsync\__init__.py", line 288, in main
    apply_sync(
  File "C:\Users\Toliak\AppData\Local\Programs\YandexDiskRSync\yandex_disk_rsync\__init__.py", line 200, in apply_sync
    yd_mkdir_recursive(options, disk_url_path.parent)
  File "C:\Users\Toliak\AppData\Local\Programs\YandexDiskRSync\yandex_disk_rsync\data.py", line 167, in yd_mkdir_recursive
    *Path(remote_path).parents[:-1]
  File "C:\Users\Toliak\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 620, in __getitem__
    if idx < 0 or idx >= len(self):
TypeError: '<' not supported between instances of 'slice' and 'int'
```

**Comment by Toliak** [comment]
There is a compatibility behavior with lower python version

https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.parents
> Changed in version 3.10: The parents sequence now supports slice and negative index values.
