### ISSUE TITLE
ydcmd is broken with python 3.12, 3.13, etc

### ISSUE THREAD

**Issue by mal19992** [Toliak/YandexDiskUploader#4]
ydcmd ls

```
/usr/bin/ydcmd:888: SyntaxWarning: invalid escape sequence '\/'
  if re.match('^https:\/\/[a-z0-9\.\-]+\.yandex\.(net|ru|com|ua|by|kz|az|ee|fr|kg|lt|lv|md|tj|tm|com\.tr|co\.il|com\.am)(:443){,1}\/', url, re.IGNORECASE) == None:
/usr/bin/ydcmd:2638: SyntaxWarning: invalid escape sequence '\S'
  regexp = re.compile("^--(\S+?)(=(.*)){,1}$")
Traceback (most recent call last):
  File "/usr/bin/ydcmd", line 2670, in <module>
    yd_ls_cmd(options, args)
    ~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/bin/ydcmd", line 1990, in yd_ls_cmd
    result = listvalues(yd_list(options, yd_remote_path(path)))
                        ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/ydcmd", line 1107, in yd_list
    part = yd_query(options, method, url, args)
  File "/usr/bin/ydcmd", line 969, in yd_query
    return yd_query_retry(options, method, url, args, headers, target, data)
  File "/usr/bin/ydcmd", line 905, in yd_query_retry
    result = opener.open(request, timeout = options.timeout)
  File "/usr/lib64/python3.13/urllib/request.py", line 489, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.13/urllib/request.py", line 506, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
                              '_open', req)
  File "/usr/lib64/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/bin/ydcmd", line 414, in https_open
    return self.do_open(self._get_connection, req)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/urllib/request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              encode_chunked=req.has_header('Transfer-encoding'))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/ydcmd", line 315, in request
    self._send_request(method, url, body, headers, **kwargs)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/ydcmd", line 371, in _send_output
    self.send(msg)
    ~~~~~~~~~^^^^^
  File "/usr/bin/ydcmd", line 383, in send
    self.connect()
    ~~~~~~~~~~~~^^
  File "/usr/bin/ydcmd", line 276, in connect
    if self.cert_file is not None:
       ^^^^^^^^^^^^^^
AttributeError: 'ydHTTPSConnection' object has no attribute 'cert_file'
```

Here the regex does not use raw string, and python api has changes, the  field cert_file was removed from python API

**Comment by mal19992** [comment]
wrong project post
